-- DAP configuration automatically generated by :GenLaunch on Tue Jul 15 17:19:57 2025
-- This file uses the PROJECT_DAP_CONFIGS table structure.

-- You can define project-specific adapters here if needed.
-- The global adapters at the time of generation are included below.
local dap = require('dap')
dap.adapters = {
  codelldb = {
    executable = {
      args = { "--port", "${port}" },
      command = "/home/yadard/.local/share/nvim/mason/bin/codelldb"
    },
    port = "${port}",
    type = "server"
  },
  python = {
    args = { "-m", "debugpy.adapter" },
    command = "/usr/bin/python",
    type = "executable"
  }
}

	DAP_PRE_LAUNCH_TASK = "gcc main.c -g"
-- This table holds all named debug configurations for the project.
-- The 'default' label is special: it will be loaded automatically on startup.
PROJECT_DAP_CONFIGS = {
  default = {
    cwd = "${workspaceFolder}",
    filetype = "c",
    label = "default",
	args = {
	   "./assets/Bible.txt",
	   "Jesus"
   },
    name = "Launch file",
    program = "${workspaceFolder}/a.out",
    request = "launch",
    stopOnEntry = false,
    type = "codelldb"
  }
}
